### ISSUE TITLE
Is it OK to use Jupiter EX?

### ISSUE THREAD

**Issue by codeonwort** [Katana-Steel/lithtech#10]
Hi. I don't know where to ask so I'm asking here. Sorry if this is not the right place.

I first found Jupiter EX here:
https://github.com/jsj2008/lithtech

I wanted to fork and modify it, but couldn't find any clues that Jupiter EX ever was released as GPL by Touchdown Entertainment, so I was afraid of if there will be some legal issues. But you are actively developing this fork, so may I ask if you know anything about it; is it perfectly fine to use the GPL-claiming source code?

**Comment by hogsy** [comment]
I could be wrong but I've heard a few sources say that this was leaked and not actually an official release by Touchdown Entertainment, and I haven't heard otherwise in any official capacity.

It would be nice if someone could get in touch with someone from Monolith to get an _official_ word to clear this up but for now I think you should probably be cautious.

**Comment by Katana-Steel** [comment]
@hogsy is correct... it would be nice with official word
however freetype bundle has been release under GPL v2...
if you have the desire, all my modifications are here for my benefit and when get time
I'll add a license on all the files I've added. The license I'll be using will be the GNU GPL v3 where possible.
